GOOSE_MAX_TURNS: 10
GOOSE_MODE: smart_approve
GOOSE_CLI_MIN_PRIORITY: 0.0
extensions:
  developer:
    available_tools: []
    bundled: true
    description: null
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  duckduckgo-mcp-server:
    args:
      - duckduckgo-mcp-server
    bundled: null
    cmd: uvx
    description: null
    enabled: true
    env_keys: []
    envs: {}
    name: duckduckgo-mcp-server
    timeout: 300
    type: stdio
  memory:
    available_tools: []
    bundled: true
    description: null
    display_name: Memory
    enabled: true
    name: memory
    timeout: 300
    type: builtin
